/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_pan_myproject_jni_JniTest */

#ifndef _Included_com_project_pan_myproject_jni_JniTest
#define _Included_com_project_pan_myproject_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_pan_myproject_jni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_project_pan_myproject_jni_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_project_pan_myproject_jni_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_project_pan_myproject_jni_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
